services:
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    env_file: ".env"
    depends_on:
      - qdrant
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

volumes:
  qdrant_storage:

networks:
  app-network:
    driver: bridge